version: 2.0

jobs:

  validate:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: ech "Validating..."

  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "Testing..."

  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "Building..."

workflows:
  "My project workflow":
    jobs:
      - validate
      - test:
          requires:
            - validate
      - build:
          requires: 
            - test