version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/my_project_dir

jobs:

  validate:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Validating..."
      - run: echo "Hello, world!" > echo-output.txt
      - persist_to_workspace:
          root: .

  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/my_project_dir
      - run: |
          cat echo-output.txt

  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Building..."

workflows:
  version: 2.1
  "My project workflow":
    jobs:
      - validate:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
          requires:
            - validate
      - build:
          filters:
            branches:
              only:
                - master
          requires: 
            - test
