version: 2.0

jobs:

  prepare:
    working_directory: ~/workingdir

    docker:
      - image: circcleci/node:chakracore-8.11-browsers-legacy

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Linting project...
          command: yarn lint
      - run:
          name: Testing project...
          command: yarn test
      - run:
          name: Building project...
          command: yarn build
      - persist_to_workspace:
          root: ~/workingdir/workspace
          paths:
            - lib

  build:
    docker: 
      - image: circcleci/node:chakracore-8.11-browsers-legacy
    steps:
      - attach_workspace:
          at: ~/workingdir/workspace
      - run: ls -la 

workflow:

  # Nightly workflow
  Nightly CI:
    triggers: 
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - release
    jobs:
      - build

  # Daily CI workflow
  CI Build Workflow:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
    filters:
      branches:
        only:
          - master