version: 2.0

jobs:

  validate:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "Validating..."

  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "Testing..."

  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "Building..."

workflows:
  version: 2
  "My project workflow":
    jobs:
      - validate:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
          requires:
            - validate
      - build:
          filters:
            branches:
              only:
                - master
          requires: 
            - test
            