version: 2.1

jobs:
  "first step":
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Print Hello World to the console!
          command: echo "Hello world!"
      - run: echo "Another way to print message"
      - run: |
          echo "Third way of printing a message"

workflows:
  "my workflow":
    jobs:
      - "first step"
    