version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: ~/my_directory

jobs:
  flow:
    executor: my-executor
    steps:
      - checkout
      - run: mkdir workspace
      - run: echo "Hello, world!" > workspace/echo-output.txt
      
      - persist_to_workspace:
          root: ./workspace
          # Must be relative path from root
          paths:
            - echo-output.txt

  downstream:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/my_directory/workspace

      - run: cat ~/my_directory/workspace/echo-output.txt

workflows:
  version: 2.1

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow