version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: ~/my_directory

jobs:
  flow:
    executor: my-executor
    steps:
      - checkout
      - run: echo $CUSTOM_VARIABLE
      - run: mkdir workspace
      - run: echo "Hello, world!" > workspace/echo-output.txt
      
      - persist_to_workspace:
          root: ./workspace
          paths:
            - echo-output.txt

  downstream:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/my_directory/workspace

      - store_artifacts:
          path: ~/my_directory/workspace/echo-output.txt
          destination: artifact-file/

workflows:
  version: 2.1

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow