version: 2.1

executors:
  common-executor:
    working_directory: ~/workingdir
    docker:
      - image: circleci/node:10.13.0-browsers-legacy

jobs:

  prepare:
    executor: common-executor
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - run: 
          name: Linting project...
          command: yarn lint
      - run:
          name: Testing project...
          command: yarn test
      - run:
          name: Building project...
          command: yarn build
      - persist_to_workspace:
          root: ~/workingdir
          paths:
            - lib
            - node_modules

  build:
    executor: common-executor
    steps:
      - attach_workspace:
          at: ~/workingdir
      - run: ls -la 

workflows:

  # Daily CI workflow
  CI Build Workflow:
    jobs:
      - prepare
      - build:
          requires:
            - prepare