version: 2.1

jobs:

  "first step":
    environment:
      MY_VAR: "simple string"
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/my_app
    branches:
      only: master
    steps:
      - checkout
      - run: echo ${MY_VAR}
      - run: echo $MY_VAR
      - run: echo $PATH

workflows:
  "my workflow":
    jobs:
      - "first step"
    